name: Create release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-datapack:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    strategy:
      matrix:
        # Use these Java versions
        java: [ 21 ]
        # and run on both Linux and Windows
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: build
        run: ./gradlew chiseledBuild